language: objective-c
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
env:
  global:
  - FRAMEWORK_NAME=EECellSwipeGestureRecognizer
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script:
- travis_retry xcodebuild -workspace EECellSwipeGestureRecognizer.xcworkspace -scheme "EECellSwipeGestureRecognizer" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
deploy:
  provider: releases
  api_key:
    secure: DMctqY37Yfzb0yvDOp2Wh+qgeuTkI/XwWL2RGBOteN2wwYRMhASjRXzRlZhTKevJ15QpunjOVbOUtZe3ROkGFVMJv4AAe1s32cBRrtIYth/1UAbQ4rphh6qsaUOTgJwTQ85jP6thNX8c5BQzfvkuADmEduC+ab1wS7gM6JwHBfzKSN1Ugmje4uZRhv08mBiRgEdfyib5qxOXONQON4OGGC4xqaD7mkOvdS75H+6CW7uR0W/Iq0qunTXOWcVi2x4xFn6XNTBGo8Qr8xjC0oAtuRDgCf14AEJz6rzi34Ht1HJzXOUP7/OdEuvUyvOyIQHyPGQbu4Quz/fAmP9kTBUB58F2wbauOmSr+HFcH/j8trhAzEJgx1rvwcnnnaC8WAPVxthvUKo7Mum8peOLpy1UD6wD6BcQyS8+/XgVTVj+6rTqXC/IGGXk5lztN24Voyg6nmi3yNUkgf56FJEZIjNps5Bvp/VelrvyTFBigofUE8xgevbqdjsNEPCGMJpkVZePZITgk8v8/qRUS8icmtfN2l3d5fleOC9dCivtFb9cE/A4cwGz6zSnx/sZr1IRy8QzUYpgLs4xDJFWqNVqb2vTefToEdjSqQGus2qxVKEgLcQSE5ZX5Q+K6Cy340W1PvRp78K/x6LSN5BdcZ083oWQZliYQqZZLX/nVAo3DwVofIY=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: enricenrich/EECellSwipeGestureRecognizer
    tags: true
